server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<segment>.*), /order/$\{segment}
        - id: goods-service
          uri: lb://GOODS-SERVICE
          predicates:
            - Path=/goods/**
          filters:
            - RewritePath=/goods/(?<segment>.*), /goods/$\{segment}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 