global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']

  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 3s
    scrape_timeout: 2s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_memory_used_bytes|jvm_gc_pause_seconds|http_server_requests_seconds|tomcat_threads_.*'
        action: keep

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']